Pipeline:
  name: DeepDocGenV2
  version: 1.0
  description: DeepDocGen pipeline for generating syntetic documents
  git_repo: https://github.com/ICA-PUC/Synthetic_document_pipeline

Pdf_selector:
  should_perform: True
  Parameters:
    process_output_path: D:/Meus_codigos_de_mestrado/Synthetic_document_pipeline/Pipeline_annotation_output/
    documents_Pdf_path: D:/Meus_codigos_de_mestrado/Synthetic_document_pipeline/pdf_folder/
    desired_folder_name: pdfs_to_image
    desired_image_format: png
    image_resize_size: [224, 224]
    is_fine_tuned_model: True
    path_to_fine_tuned_model: D:/Meus_codigos_de_mestrado/Synthetic_document_pipeline/Pipeline_annotation_output/fine_tuned_model/swin_t_finetuned_20_ep.pth
    path_to_download_model:
    desired_model_folder_name:
    deep_learning_model_name: swin_t
    deep_learning_model_weights: 
    batch_size: 1
    num_channels: 3
    should_shuffle_dataset: False
    should_save_embedding_extracted: True
    desired_cluster_list: [2, 20]
    clustering_method: silhouette
    n_init: auto 
    random_state: 42
    reduction_method: tsne # pca, umap, lda, mds, isomap, ded
    desired_perplexity_range_for_tsne: [5, 50, 5]
    how_many_components: 2
    t_SNE_initializer: pca
    should_save_best_embedding: True
    desired_dataframe_columns_name: embedding_
    should_convert_dataframe_to_excel: True

Post_processor_to_publaynet:
  should_perform: False
  Parameters:
    path_to_the_vott_file: D:/Meus_codigos_de_mestrado/Synthetic_document_pipeline/Pipeline_annotation_output/vott_file/Group_12_annotation-export.json
    image_id_starter: 1
    annotation_id_starter: 200
    path_to_save_publyanet_format : D:/Meus_codigos_de_mestrado/Synthetic_document_pipeline/Pipeline_annotation_output/
    desired_name: test_pipeline_v2

Layout_generator_process:
  should_perform: False
  name: LayoutTransformer
  version: 1.0
  description: LayoutTransformer model for generating document layout
  git_repo: https://github.com/kampta/DeepLayout
  Parameters:
    experience_name: Layout_Transformer_Inference_12_11_2024
    dataset_path: D:/Meus_codigos_de_mestrado/Synthetic_document_pipeline/Pipeline_annotation_output/group_1_publyanet.json
    model_trained_path: D:/Meus_codigos_de_mestrado/Synthetic_document_pipeline/Pipeline_annotation_output/model/hub/checkpoints/layout_generator.pth
    max_length: 512
    precision: 16
    seed: 42
    batch_size: 1
    n_layers: 6
    n_embd: 512
    n_heads: 8
    temper: 0.7
    top_k: 10
    generate_image_range: 2
    generate_image_path: D:/Meus_codigos_de_mestrado/Synthetic_document_pipeline/Pipeline_annotation_output/image_layout
    generate_coords_path: D:/Meus_codigos_de_mestrado/Synthetic_document_pipeline/Pipeline_annotation_output/image_coords

Post_process_to_remove_overlap:
  should_perform: False
  Parameters:
    layout_gener_coord_path: D:/Meus_codigos_de_mestrado/Synthetic_document_pipeline/Pipeline_annotation_output/image_coords
    vmin: 0.4
    vmax: 0.5
    where_to_save_reconstructed_image: D:/Meus_codigos_de_mestrado/Synthetic_document_pipeline/Pipeline_annotation_output/Pipeline_annotation_output/
    where_to_save_reconstructed_coords: D:/Meus_codigos_de_mestrado/Synthetic_document_pipeline/Pipeline_annotation_output/Pipeline_annotation_output/

Content_generator_process:
  should_perform: False
  Parameters:
    test_mode: False
    verbose: False
    config_path: D:/Meus_codigos_de_mestrado/Synthetic_document_pipeline/src/Synthetic_document_pipeline/content_generator/content_src/config.json
    input_path: D:/Meus_codigos_de_mestrado/Synthetic_document_pipeline/Pipeline_annotation_output/content_generator_test/Group_3_corrected_coords
    output_path: D:/Meus_codigos_de_mestrado/Synthetic_document_pipeline/Pipeline_annotation_output/   

Post_process_to_coco_format:
  should_perform: False 
  parameters:
    process_output_path:  D:/Meus_codigos_de_mestrado/Synthetic_document_pipeline/Pipeline_annotation_output/
    document_image_path:  D:/Meus_codigos_de_mestrado/Synthetic_document_pipeline/Pipeline_annotation_output/dataset_23_01_2025
    annotation_xml_path: D:/Meus_codigos_de_mestrado/Synthetic_document_pipeline/Pipeline_annotation_output/dataset_23_01_2025
    image_witdh: 1200
    image_height: 1600
    how_many_data_split: 2
    training_percentage: 0.8
    validation_percentage: 0.2
    test_percentage: 
    should_shuffle_data: True
    random_seed: 42
    which_segmentation_method: only_block
    category_list_dict: [{"name": "text"},
                         {"name": "title"},
                         {"name": "list"},
                         {"name": "table"},
                         {"name": "image"}]
    should_visualize_image: False
    
Post_process_to_yolo_format:
  should_perform: False
  Parameters:
    process_output_path: D:/Meus_codigos_de_mestrado/Synthetic_document_pipeline/Pipeline_annotation_output/Pipeline_annotation_output/